runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: bearcats23!
  CLOUD_SQL_DATABASE_NAME: users
  CLOUD_SQL_CONNECTION_NAME: sabrosa:us-east1:sabrosa-1

runtime_config:
 python_version: 3